"""create ioc_enrichments table

Revision ID: 542b407834c4
Revises: add316fbc400
Create Date: 2026-07-13 20:45:41.033403

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "542b407834c4"
down_revision: Union[str, Sequence[str], None] = "add316fbc400"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ioc_enrichments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("indicator_type", sa.String(length=20), nullable=False),
        sa.Column("indicator_value", sa.String(length=255), nullable=False),
        sa.Column("abuseipdb_score", sa.Integer(), nullable=True),
        sa.Column("abuseipdb_total_reports", sa.Integer(), nullable=True),
        sa.Column("otx_pulse_count", sa.Integer(), nullable=True),
        sa.Column("otx_malware_families", sa.ARRAY(sa.String()), nullable=False),
        sa.Column("combined_threat_score", sa.Integer(), nullable=False),
        sa.Column(
            "raw_abuseipdb", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("raw_otx", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "indicator_type", "indicator_value", name="uq_ioc_type_value"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ioc_enrichments")
    # ### end Alembic commands ###
