"""create case management and soar tables

Revision ID: 7dadf4ee4203
Revises: e712a8122cd1
Create Date: 2026-07-20 05:46:27.067400

Manually adjusted after autogenerate: Case.severity reuses the
alert_severity Postgres enum type (same AlertSeverity Python enum as
Alert.severity), but autogenerate doesn't recognize the type already
exists and generates a second CREATE TYPE for it, which fails against a
real database. Added create_type=False to the cases.severity column
below — the type creation already happened in the alerts-table migration.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7dadf4ee4203'
down_revision: Union[str, Sequence[str], None] = 'e712a8122cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_ips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('cases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'INVESTIGATING', 'CLOSED', name='case_status'), nullable=False),
    sa.Column('severity', postgresql.ENUM('INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity', create_type=False), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('alert_ids', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('assigned_to_id', sa.UUID(), nullable=True),
    sa.Column('created_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('playbook_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('playbook_name', sa.Enum('AUTO_TAG', 'SIMULATED_IP_BLOCK', 'AUTO_CASE_NOTIFY', name='playbook_name'), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'SKIPPED', 'FAILED', name='playbook_run_status'), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('playbook_name', 'alert_id', name='uq_playbook_alert')
    )
    op.create_table('case_comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('case_comments')
    op.drop_table('playbook_runs')
    op.drop_table('cases')
    op.drop_table('blocked_ips')
    # ### end Alembic commands ###
