"""create alerts table

Revision ID: add316fbc400
Revises: 2fe7ff1ef46d
Create Date: 2026-07-12 17:50:49.460971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'add316fbc400'
down_revision: Union[str, Sequence[str], None] = '2fe7ff1ef46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.String(length=255), nullable=False),
    sa.Column('rule_title', sa.String(length=255), nullable=False),
    sa.Column('detection_type', sa.Enum('SIGMA', 'CORRELATION', 'YARA', name='detection_type'), nullable=False),
    sa.Column('severity', sa.Enum('INFORMATIONAL', 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('mitre_techniques', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('source_event_id', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.String(length=1000), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'ACKNOWLEDGED', 'CLOSED', name='alert_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'source_event_id', name='uq_alert_rule_event')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    # ### end Alembic commands ###
