"""add ml detection type

Revision ID: e712a8122cd1
Revises: 542b407834c4
Create Date: 2026-07-15 06:46:13.987884

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e712a8122cd1"
down_revision: Union[str, Sequence[str], None] = "542b407834c4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Autogenerate doesn't reliably produce migrations for adding a value to
    an existing Postgres native enum — it's a real gap in Alembic's
    autogenerate support, not something to work around by hand-editing an
    autogenerated file. Written directly instead.
    """
    op.execute("ALTER TYPE detection_type ADD VALUE 'ML'")


def downgrade() -> None:
    """Postgres has no ALTER TYPE ... DROP VALUE — an enum value, once
    added, cannot be cleanly removed (the only real way is rebuilding the
    type from scratch and re-pointing every column, which risks data loss
    for a downgrade path nobody's exercising outside emergencies). Left as
    a deliberate no-op rather than a downgrade that silently fails or
    corrupts data — this is a known, accepted asymmetry of Postgres enums,
    not an oversight.
    """
    pass
